// Gängige Profil-/Fensterfarben für die Auswahl. Bei Bedarf hier erweitern.
export const PROFIL_FARBEN = [
  'Weiß',
  'Cremeweiß',
  'Verkehrsweiß (RAL 9016)',
  'Grauweiß (RAL 9002)',
  'Lichtgrau (RAL 7035)',
  'Fenstergrau (RAL 7040)',
  'Quarzgrau (RAL 7039)',
  'Basaltgrau (RAL 7012)',
  'Anthrazitgrau (RAL 7016)',
  'Schiefergrau (RAL 7015)',
  'Schwarzbraun (RAL 8022)',
  'Schwarz (RAL 9005)',
  'Dunkelrot (RAL 3005)',
  'Moosgrün (RAL 6005)',
  'Tannengrün (RAL 6009)',
  'Stahlblau (RAL 5011)',
  'Golden Oak',
  'Eiche dunkel',
  'Nussbaum',
  'Mahagoni',
  'Bergkiefer',
];
